include(InstallRequiredSystemLibraries)
set(CPACK_PACKAGE_CONTACT 1275345@mail.ru})

set(CPACK_PACKAGE_DESCRIPTION_SUMMARY "Singleton")
set(CPACK_RESOURCE_FILE_README ${CMAKE_CURRENT_SOURCE_DIR}/readme.md)

set(CPACK_RPM_PACKAGE_NAME "Singleton")
set(CPACK_RPM_PACKAGE_LICENSE "MIT")
set(CPACK_RPM_PACKAGE_GROUP "RK2-TIMP")
set(CPACK_RPM_PACKAGE_RELEASE 1)

set(CPACK_DEBIAN_PACKAGE_NAME "libSingleton")
set(CPACK_DEBIAN_PACKAGE_PREDEPENDS "cmake >= 3.10")
set(CPACK_DEBIAN_PACKAGE_RELEASE 1)

include(CPack)
