name: CMake Build

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v2

    - name: Create Build Directory
      run: mkdir _build

    - name: Install dependencies
      run: sudo apt-get install -y cmake gcc g++

    - name: adding GTests
      run: git submodule update --init

    - name: Configure CMake
      run: cmake -H. -B _build -DBUILD_TESTS=ON

    - name: Build
      run: cmake --build _build

    - name: Build tests
      run: cmake --build _build --target test

    - name: Artifacts
      uses: actions/upload-artifact@v4
      with:
          name: linux_artifacts
          path: ${{github.workspace}}/build/prototests
